
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-minikube
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion:
    kind: Deployment
    name: hello-minikube
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
